version: '1'
services:
  db:
    container_name: ai_db
    image: "postgres"
    volumes:
       - ./data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    expose:
      - 5432
  flaskapp:
    container_name: app
    restart: always
    build: .
    env_file:
      - .env
    volumes:
      - .:/opt/services/flaskapp/src
    ports:
      - 5000:5000
    depends_on: 
      - db